[general]
live_config_reload = true

[cursor]
blink_interval = 400

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
GDK_PIXBUF_MODULEDIR = ""
GDK_PIXBUF_MODULE_FILE = ""
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 15.0

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Monospace"

[font.offset]
x = 0
y = -2

[window]
dynamic_title = true
opacity = 0.95

[window.class]
general = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0
